services:
  #"cérebro"
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
  # Descomente abaixo SE tiver GPU NVIDIA e o NVIDIA Container Toolkit instalado
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
  
  #memória
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  #o agente
  ai-agent:
    build: .
    ports:
      - "5000:5000"
    container_name: flask_ai_agent
    networks:
      - rede-agentes-fraude
    depends_on:
      - ollama
      - redis
    environment:
      - OLLAM_HOST=http://ollama:11434
      - AGENT_MODEL=qwen3.5:0.8b
      - REDIS_HOST=redis
      #aponta para o nome do serviço kafka na aplicação principal("app")
      - KAFKA_BROKER=kafka:29092

volumes:
  ollama_data:

networks:
  rede-agentes-fraude:
    external: true